apiVersion: v1
kind: ConfigMap
metadata:
  name: carbon-scheduler-configmap
  namespace: kube-system
data:
  carbon-scheduler-config: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: kube-carbon-scheduler
        plugins:
          score:
            enabled:
              - name: carbon
    leaderElection:
      leaderElect: false
