apiVersion: v1
kind: ConfigMap
metadata:
  name: carbon-scheduler-configmap
data:
  carbon-scheduler-config: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: kube-carbon-scheduler
        plugins:
          score:
            disabled:
              - name: ImageLocality
              - name: TaintToleration
              - name: NodeAffinity
              - name: PodTopologySpread
              - name: NodeResourcesFit
              - name: NodeResourcesBalancedAllocation
              - name: VolumeBinding
              - name: InterPodAffinity
            enabled:
              - name: carbon