apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: my-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
    spec:
      serviceAccountName: kube-carbon-scheduler
      containers:
        - command:
            - --scheduler-name=kube-carbon-scheduler
            - --config=/etc/carbon-scheduler-config
            - --v=4
          image: thandayuthapani/kube-carbon-scheduler
          name: kube-carbon-scheduler
          volumeMounts:
            - name: config
              mountPath: /etc/admiralty
      hostNetwork: false
      hostPID: false
      volumes:
        - name: config
          configMap:
            - name: carbon-scheduler-configmap