apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}
  labels: {{ include "labels" . | nindent 4 }}
data:
  proxy-scheduler-config: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      resourceName: admiralty-proxy-scheduler
      resourceNamespace: {{ .Release.Namespace }}
      resourceLock: leases
    profiles:
      - schedulerName: admiralty-proxy
        plugins:
          score:
            disabled:
              - name: ImageLocality
              - name: TaintToleration
              - name: NodeAffinity
              - name: PodTopologySpread
              - name: NodeResourcesFit
              - name: NodeResourcesBalancedAllocation
              - name: VolumeBinding
              - name: InterPodAffinity
          multiPoint:
            enabled:
              - name: proxy
  candidate-scheduler-config: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      resourceName: admiralty-candidate-scheduler
      resourceNamespace: {{ .Release.Namespace }}
      resourceLock: leases
    profiles:
      - schedulerName: admiralty-candidate
        plugins: 
          multiPoint:
            enabled:
              - name: candidate
