---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sources.multicluster.admiralty.io
  labels: {{ include "labels" . | nindent 4 }}
spec:
  group: multicluster.admiralty.io
  names:
    kind: Source
    plural: sources
    shortNames:
      - src
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                userName:
                  type: string
                serviceAccountName:
                  type: string
            status:
              type: object
