apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "fullname" . }}
spec:
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-cluster-critical
