---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustersummaries.multicluster.admiralty.io
  labels: {{ include "labels" . | nindent 4 }}
spec:
  group: multicluster.admiralty.io
  names:
    kind: ClusterSummary
    plural: clustersummaries
    shortNames:
      - mcsum
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          properties:
            capacity:
              type: object
              additionalProperties:
                x-kubernetes-int-or-string: true
            allocatable:
              type: object
              additionalProperties:
                x-kubernetes-int-or-string: true
