---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustersources.multicluster.admiralty.io
  labels: {{ include "labels" . | nindent 4 }}
spec:
  group: multicluster.admiralty.io
  names:
    kind: ClusterSource
    plural: clustersources
    shortNames:
      - csrc
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                userName:
                  type: string
                serviceAccount:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
            status:
              type: object
