---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustertargets.multicluster.admiralty.io
  labels: {{ include "labels" . | nindent 4 }}
spec:
  group: multicluster.admiralty.io
  names:
    kind: ClusterTarget
    plural: clustertargets
    shortNames:
      - ctg
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                self:
                  type: boolean
                kubeconfigSecret:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                    key:
                      type: string
                    context:
                      type: string
                excludedLabelsRegexp:
                  type: string
            status:
              type: object
