---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podchaperons.multicluster.admiralty.io
  labels: {{ include "labels" . | nindent 4 }}
spec:
  group: multicluster.admiralty.io
  names:
    kind: PodChaperon
    plural: podchaperons
    shortNames:
      - chap
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              # TODO generate
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              # TODO generate
      additionalPrinterColumns:
        - name: reserved
          type: string
          jsonPath: .metadata.annotations.multicluster\.admiralty\.io/is-reserved
        - name: allowed
          type: string
          jsonPath: .metadata.annotations.multicluster\.admiralty\.io/is-allowed
