apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow
rules:
# pod get/watch is used to identify the container IDs of the current pod
# pod patch is used to annotate the step's outputs back to controller (e.g. artifact location)
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - patch
# logs get/watch are used to get the pods logs for script outputs, and for log archival
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
# secrets get is used to retrieve credentials to artifact repository. NOTE: starting n Argo v2.3,
# the API secret access will be removed in favor of volume mounting the secrets to the workflow pod
# (issue #1072)
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow
subjects:
- kind: ServiceAccount
  name: argo-workflow
