apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fullname" . }}-post-delete-hook
  labels: {{ include "labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fullname" . }}-post-delete-hook
subjects:
  - kind: ServiceAccount
    name: {{ include "fullname" . }}-post-delete-hook
    namespace: {{ .Release.Namespace }}
