apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fullname" . }}-post-delete-hook
  labels: {{ include "labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
